package TestApp;


/**
* TestApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./testapp.idl
* Thursday, June 11, 2026 11:17:17 PM IST
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
