package TestApp;


/**
* TestApp/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./testapp.idl
* Thursday, June 11, 2026 11:17:17 PM IST
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
