package TestApp;

/**
* TestApp/HelloHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./testapp.idl
* Thursday, June 11, 2026 11:17:17 PM IST
*/

public final class HelloHolder implements org.omg.CORBA.portable.Streamable
{
  public TestApp.Hello value = null;

  public HelloHolder ()
  {
  }

  public HelloHolder (TestApp.Hello initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TestApp.HelloHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TestApp.HelloHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TestApp.HelloHelper.type ();
  }

}
